export const menuItemsData = [
  {
    id: 1,
    name: 'Carrot',
    info: 'Sweet and crunchy root vegetable, high in beta-carotene, vitamin A, and antioxidants. Great raw or cooked.',
    price: 19,
    img: '/images/carrot.png',
  },
   
  {
    id: 2,
    name: 'Apples',
    info: 'Crunchy, juicy fruit that comes in a variety of colors and flavors. High in fiber, antioxidants, and vitamin C.',
    price: 30,
    img: '/images/apples.png',
  },
  {
    id: 3,
    name: 'Tomato',
    info: 'Sweet and juicy fruit, high in calcium, vitamin C, and vitamins.',
    price: 18,
    img: '/images/tomotos.png',
  },
  {
    id: 4,
    name: 'Cucumber',
    info: 'Crisp, refreshing vegetable with a mild, watery flavor. Great in salads, sandwiches, or as a healthy snack.',
    price: 21,
    img: '/images/cucumber.png',
  },
  {
    id: 5,
    name: 'Potato',
    info: 'Starchy, versatile vegetable that comes in many varieties. High in vitamin C, potassium, and fiber. Great for frying, baking, boiling, or mashing.',
    price: 28,
    img: '/images/potato.png',
  },
  {
    id: 6,
    name: 'Beans',
    info: 'Nutritious legumes that come in many varieties. High in protein, fiber, and iron. Great in soups, salads, or as a side dish.',
    price: 22,
    img: '/images/beans.png',
  },
  {
    id: 7,
    name: 'kiwi',
    info: 'Small, fuzzy fruit with a tangy-sweet flavor and bright green flesh. High in vitamin C and fiber. Great in salads or as a snack.',
    price: 27,
    img: '/images/kiwi.png',
  },
  {
    id: 8,
    name: 'water melon',
    info: 'Juicy, refreshing fruit with a sweet, crisp flavor. High in vitamin C and lycopene. Perfect for summertime snacking or in salads.',
    price: 24,
    img: '/images/watermelon.png',
  },
  {
    id: 9,
    name: 'Grapes',
    info: 'Juicy, refreshing fruit with a sweet, crisp flavor. High in vitamin C and lycopene. Perfect for summertime snacking or in salads.',
    price: 22,
    img: '/images/grapes.png',
  },
  {
    id: 10,
    name: 'Orange',
    info: 'Sweet, juicy citrus fruit thats high in vitamin C and fiber. Great for snacking, juicing, or in salads.',
    price: 22,
    img: '/images/orange.png',
  },
  {
    id: 11,
    name: 'Dragon Fruit',
    info: 'Exotic fruit with a vibrant pink or yellow exterior and white or pink speckled flesh. Mildly sweet flavor with a crunchy texture.',
    price: 32,
    img: '/images/dragonfruit.png',
  },
  {
    id: 12,
    name: 'Lady figures',
    info: 'Light, sponge-like cookies that are long and narrow in shape. Often used in desserts like tiramisu or trifle',
    price: 14,
    img: '/images/ladyfigure.png',
  },
  {
    id: 13,
    name: 'Pine Apple',
    info: 'Sweet, juicy tropical fruit with a spiky exterior and yellow flesh. High in vitamin C and bromelain. Great for snacking or in salads.',
    price: 24,
    img: '/images/pineapple.png',
  },
  {
    id: 14,
    name: 'Cabbage',
    info: 'Leafy, round vegetable thats a good source of vitamin C and fiber. Great for coleslaw, salads, or cooked dishes.',
    price: 19,
    img: '/images/cabbage.png',
  },
  {
    id: 15,
    name: 'Beat Root',
    info: 'Sweet, earthy root vegetable thats high in fiber and antioxidants. Great for salads, roasting, or pickling.',
    price: 18.46,
    img: '/images/beetroot.png',
  },
  {
    id: 16,
    name: 'Artichokes',
    info: 'Edible flower bud with a tough exterior and tender heart. Great for roasting, steaming, or in dips.',
    price: 20.45,
    img: '/images/Artichoke.png',
  },
  {
    id: 17,
    name: 'Onion',
    info: 'Pungent bulb vegetable with layers of papery skin. Adds flavor to a variety of dishes, raw or cooked.',
    price: 16.38,
    img: '/images/onion.png',
  },

];